### ISSUE TITLE
Running morning or link does node seem to link local dependencies

### ISSUE THREAD

**Issue by Crispy1975** [tes/bosco#101]
We're using Bosco to ease our development woes relating a to a large project with lots of micro-services that depend on each other. Not doing anything special, running either `bosco morning` or `bosco link` followed by `bosco install` does not result in `node_module` folders being populated with local dependency versions.

Unless we missing something?

Running on the latest `v0.4.0`

**Comment by dbellizzi** [comment]
What's the output when you run ``bosco install``?  Can you try running it with ``-r <reponame>`` to see if it works with a specific repository?

**Comment by Crispy1975** [comment]
Yes, will try that now and report back.

**Comment by Crispy1975** [comment]
Ok, we get a lot of errors like this when running `morning` or `install`...

	npm ERR! error: Ref refs/heads/master is at 317f06e21956e96d4e05089bd9a136a21d4bf6e6 but expected e63eb1668b05cb3cb161d89dca83beb49008c024
	npm ERR!  ! e63eb16..317f06e  master     -> master  (unable to update local ref)

Do you need to be on master branch for the linking and install to work?

**Comment by Crispy1975** [comment]
I am not so sure this is an `install` issue, more linking, when I run `bosco link` I get the following output:

	$ bosco link
	[12:12:53] Bosco: Hey man, that's a tank. And that's all it is
	[12:12:53] Bosco: Initialised using [/home/*****/.bosco/bosco.json] in environment [local] with team [*****]
	[12:12:53] Bosco: Auto linking modules together and installing deps ...
	[12:12:53] Bosco: Completed linking modules.

But I cannot find any symlinks.

**Comment by cliftonc** [comment]
Bosco link is definitely a work in progress, it was written full of optimism about how nom link works, that turned out to be all wrong!  I was never able to unpick it.

If you do a clean:

'''
bosco clean-install
'''

And then a:

'''
bosco install
'''

Does it work for you?

**Comment by Crispy1975** [comment]
@cliftonc `bosco clean-install` doesn't appear to be a valid command in the `0.4.0` version I am running? Throws up the help options...

**Comment by cliftonc** [comment]
Sorry, my bad it is

```
bosco clean-modules
```

But now I re-read your issue I'm not sure it will help other than clean up the mess link makes of your modules.

It is really tough to use npm link at scale, especially if you have any circular deps.

We link manually atm, and do it sparingly, mostly because we peg internal modules to latest so changes flow through quickly after a CI build of a module (deserving of a blog post and happy to elaborate pros and consistent).

**Comment by cliftonc** [comment]
BTW - posting from a phone hence the strange auto-correct nature of my responses!

**Comment by Crispy1975** [comment]
Blog post would be interesting.

**Comment by Crispy1975** [comment]
As a quick question relating to this, can Bosco `morning` be used without the linking part, we're having good success with `zelda` at the moment for linking, so the main thing would be to keep our many repos in sync locally and checked out on specific branches.

**Comment by cliftonc** [comment]
Morning doesn't link anymore, it only did very briefly.  What's Zelda?

**Comment by cliftonc** [comment]
Sorry - googled it ;) I'll look at using that to replace the old link command - strange I never saw it, as I did search for something that did exactly that - thanks for pointing it out.

**Comment by Crispy1975** [comment]
Ah cool.

Zelda is an npm linker: `https://github.com/feross/zelda`

Ah, you beat me to it. ;-)
