### ISSUE TITLE
Set flat npmClean or something which will delete node_modules and install all packages

### ISSUE THREAD

**Issue by aamirafridi** [tes/bosco#102]
It would be nice to run ```bosco morning npmclean``` which will ```rm -rf node_modules``` from each repo and than do ```npm install```. I know we can do ```npm prune``` but it didn’t worked for me and has some issues.

It will take time but it make sure that it removes all unwanted packages from node_modules.

**Comment by cliftonc** [comment]
There are two commands that already do this:

```
bosco clean-modules
bosco install
```

You could create a composite command (e.g. like restart), that called these two if you use them a lot and submit a PR?

example:  https://github.com/tes/bosco/blob/master/commands/restart.js

**Comment by aamirafridi** [comment]
I don't use them a lot and we shouldn't. Its good to run it after every 2/3 weeks because people remove packages from packages.json those packages still exists in node_modules which sometime cause issues where tests passes locally but fails on jenkins. ```bosco clean-modules``` is all I need.
May be when we run ```bosco morning``` on Monday between 9-11am, it will clean modules, otherwise it will run normally :ghost:
