### ISSUE TITLE
aws-keys not found when running cdn

### ISSUE THREAD

**Issue by cliftonc** [tes/bosco#105]
```
[04:36:44] Bosco: ./aws-keys not found, deployment will not work unless these are created.
```

Can't find this anywhere in the code - so looks like it is coming from a library, looked in ```knox```, also couldn't find it there.

**Comment by geophree** [comment]
I'm pretty sure that's from a project's build, I don't remember which one offhand though.

**Comment by cliftonc** [comment]
I'll find it.
