### ISSUE TITLE
We're using both blanket and istanbul

### ISSUE THREAD

**Issue by geophree** [tes/bosco#106]
@cliftonc We use istanbul for coverage in `npm test`, but then use blanket in `npm coverage`.  Why?  From what I've read online, we should be able to use istanbul for the coveralls stuff too.  Something like:

``` bash
npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
```

**Comment by cliftonc** [comment]
Probably just showing its age,  I don't think you could when first written.  Let's simplify it.

**Comment by geophree** [comment]
So I reworked the npm scripts.  Right now the travis build is using `npm run coveralls` which re-runs the tests, we should be able to switch it to `npm run coveralls-after-test` so that it can just re-use the coverage reports generated by the test run.  Unfortunately, I don't know how to do that.

**Comment by geophree** [comment]
Also, sorry about tanking our coverage by using `--include-all-sources`.  :cry: It was necessary, I think.

**Comment by cliftonc** [comment]
Agreed, it would be nice to factor enough out of the commands into core lib that we can start testing commands with a few simple git / fs mocks.

**Comment by rouanw** [comment]
Bosco uses nyc these days.
