### ISSUE TITLE
Next release should be 0.5

### ISSUE THREAD

**Issue by geophree** [tes/bosco#112]
I think our next release should be 0.5, my arg changes aren't backwards-compatible with commands that use old-style args.

**Comment by cliftonc** [comment]
Fine by me, go for it whenever you are ready.

**Comment by cliftonc** [comment]
I've fixed a few of the other smaller, long standing issues - so this will make 0.5 a bit meatier.  Do we want to wait include fixes to any of the other issues?

- [ ] https://github.com/tes/bosco/issues/106
- [ ] https://github.com/tes/bosco/issues/109
- [ ] https://github.com/tes/bosco/issues/100

?

**Comment by geophree** [comment]
#106 is fixed, the issue is still open only to change the travis config to use `npm run coveralls-after-test` instead of `npm run coveralls`, so that we aren't running tests twice.

As for the others, I don't think we need to wait on them.

**Comment by geophree** [comment]
I am moving us to eslint right now.  We may want to wait on that.  Also, I really should have finished it on Friday, now I have to merge in all your changes.  :laughing:

**Comment by cliftonc** [comment]
@geophree - good to close?
