### ISSUE TITLE
Missing/broken files

### ISSUE THREAD

**Issue by cjcheshire** [tes/bosco#116]
It would be nice when opening http://localhost:7334/ it surfaced any files it could not locate.  Likely in red but why not add some blinking text and asteroids?

**Comment by cliftonc** [comment]
It warns in the console at the moment.

https://github.com/tes/bosco/blob/master/src/AssetHelper.js#L20

Which then causes the asset to be excluded from all following steps.  Not difficult to add an extra object type to the ```staticAssets``` array so it can be rendered on screen, but it would need a flag to allow all the subsequent steps to ignore it.

**Comment by cliftonc** [comment]
Ok, slightly different - missing files are skipped by the glob step without warning, now with warning in console.

We could add these to an object that allowed them to be rendered on page if needed?  @cjcheshire

**Comment by cliftonc** [comment]
@cjcheshire - do you want to try out from here before I publish?

``
git clone git@github.com:tes/bosco.git
cd bosco
npm link
```

Then use as normal.

**Comment by cjcheshire** [comment]
@cliftonc ah cool, i'll try this now :)

**Comment by cliftonc** [comment]
Done - I'll publish.

**Comment by cjcheshire** [comment]
Sweet, looks good!
