### ISSUE TITLE
Watching performance maybe be improved with facebook watchman

### ISSUE THREAD

**Issue by Fetz** [tes/bosco#126]
Watching files may improve if we use watchman instead of gulp watch

https://www.facebook.com/notes/facebook-engineering/watchman-faster-builds-with-large-source-trees/10151457195103920

We could do something similar as http://ember-cli.com/user-guide/#watchman to fallback in case watchman is not installed since is not a node module

**Comment by cliftonc** [comment]
Bosco doesn't actually use gulp watch, the projects do, bosco tends to just watch the one or two files it outputs.

Bosco uses watch: https://github.com/tes/bosco/blob/master/commands/cdn.js#L154

https://www.npmjs.com/package/watch

Happy to give watchman a go though and see if it helps.

**Comment by cliftonc** [comment]
Took another look and don't see a way of tying these two together, closing.
