### ISSUE TITLE
Allow adding non-org repos to be managed by bosco

### ISSUE THREAD

**Issue by gabceb** [tes/bosco#14]
I believe adding this would make bosco great to manage multiple git repos for all users including those not in a specific org. This will also make it great when sharing a public bosco project. At the moment Bosco is pretty unusable unless the person pulling the repo is part of a team inside an org. The work done by #12 makes this easier to accomplish.

I have not put too much thought into it but would love to hear other opinions. The work would involve adding repos on a different format inside the .bosco/bosco.json file and adding commands to add repos to this list.

**Comment by cliftonc** [comment]
Closing in favour of #33
