### ISSUE TITLE
Bosco shouldn't watch files

### ISSUE THREAD

**Issue by geophree** [tes/bosco#167]
Now that we have bosco checking for every time a watch build completes, we shouldn't bother watching the files, and just reload them each time the build completes.  We can do this by splitting our callback into two: one for completion of the first build, and one for completion of any build.  We would use the first callback to advance to the next build in `cdn` and the second to reload any files.

**Comment by cliftonc** [comment]
We need to go and find all the services that Bosco actually does do the build and minification for (perhaps a few old ones left without separate build tasks?), and write build tasks for them before we can completely remove it (took a quick look this morning and it is fairly trivial to do).

**Comment by cliftonc** [comment]
To add context, it means those services wouldn't watch in local cdn mode - not end of the world as I suspect they aren't under active development.

**Comment by geophree** [comment]
I was just saying we should be able to have cdn do its thing every time the watch build finishes, and then cdn doesn't need to watch files itself.  We can still have cdn doing do bundling, minification, etc.

**Comment by cliftonc** [comment]
It still does it thing, the watch code was actually pointless since we made the change to read files watched from disk and not from the in memory cache.

**Comment by cliftonc** [comment]
Merged.
