### ISSUE TITLE
bosco cdn should fail if a dependency listed in bosco-service.json is not available in the team

### ISSUE THREAD

**Issue by bettiolo** [tes/bosco#173]
If my `bosco-service.json` lists dependency `service-a` but the dependency is not on the disk / in the team, `bosco cdn` will not output any error about not being able to find it to build it.

**Comment by cliftonc** [comment]
This has been superceded by the new runlist + cdn proxy, so it will actually run missing services via Docker and then proxy the assets for missing services to S3 and so always serve them.
