### ISSUE TITLE
bosco run should display an error if a dependency listed in bosco-service.json cannot be found

### ISSUE THREAD

**Issue by bettiolo** [tes/bosco#174]
If my `bosco-service.json` has a dependency that cannot be found on the disk, no warnings or errors are being displayed.

**Comment by geophree** [comment]
It also looks for them on github, but it can't run node services that way.

**Comment by cliftonc** [comment]
If it isn't part of the team it has no info on it - so it goes to github to find out what sort of service it is.  We can easily make it display a list of missing dependencies as part of the run list step, somewhat surprising that it doesn't already.

**Comment by cliftonc** [comment]
PR above goes someway to addressing this.

**Comment by cliftonc** [comment]
This is superceded with the recent run dependent services as containers model.
