### ISSUE TITLE
If CDN watch fails for any reason, the watch command will not be executed anymore, should be re-executed

### ISSUE THREAD

**Issue by bettiolo** [tes/bosco#175]
![screen shot 2016-09-20 at 17 10 16](https://cloud.githubusercontent.com/assets/1333608/18678805/3308b49e-7f55-11e6-8eee-0ca9d07c9efc.png)

**Comment by geophree** [comment]
This is similar to the service restart problem.  How often do we want to restart?  Is there a limit on the number of times we try?  Watch commands dying point to an error in the user's code that needs to be fixed.

**Comment by bettiolo** [comment]
I would say that in both scenario, wait 1 second before restart, it will make it apparent that the service is not starting or the build is failing. In my example it is failing because the watch command doesn't end always with the same message.

**Comment by cliftonc** [comment]
If your watch command doesn't always end with the same message then you need to change your build so that it does - this is a negative result of us changing the way the runner works, looking only at stdout and not maintaining any state.  

If you get any text at all after the watch finished text, then it assumes a new build has started.

We should probably add a small delay, ignore any stdout for ~1 second after we get the watch text before waiting again, but this just masks the problem that your build can finish with different outputs.

**Comment by bettiolo** [comment]
These are two separate issues, I agree that if my output is bad I need to fix it, but it is outside the scope of what I am doing right now.

The issue is that the watch command should be re-executed if the build fails. Example, wrong syntax and the transpilers will fail and webpack will error out and the watch command will never be executed again, causing me to slow down and have to restart the whole cdn.

**Comment by bettiolo** [comment]
Example: 
<img width="649" alt="screen shot 2016-09-26 at 12 36 46" src="https://cloud.githubusercontent.com/assets/1333608/18832935/0bbdc736-83e6-11e6-90cc-b919cfaa5142.png">

I think that it is reasonable that my timeout exceeds, the watch should try again.

I think that we should also improve these part of the error:

```
[06:44:41] Bosco: Error: Build timed out beyond 30 seconds
    at Timeout.onBuildTimeout (/Users/mbettiolo/Code/tes/bosco/src/ExternalBuilders/SpawnWatch.js:30:29)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[06:44:41] Bosco: Watch command for app-resource died with code null
[06:44:41] Bosco: Failed build command for app-resource:
[06:44:41] Bosco: Error: Watch process exited with code null and signal SIGTERM
    at ChildProcess.onChildExit (/Users/mbettiolo/Code/tes/bosco/src/ExternalBuilders/SpawnWatch.js:65:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

If the build of a project timed out, we should just display that instead of 4 lines with stack traces.

**Comment by bettiolo** [comment]
Fun that it changes the date formatting: 
<img width="123" alt="screen shot 2016-09-26 at 12 41 12" src="https://cloud.githubusercontent.com/assets/1333608/18833029/8dedb43c-83e6-11e6-8028-ec6c806d57b6.png">

**Comment by cliftonc** [comment]
Agree we shouldn't show those errors, they are a bit odd.

In the old model it only looked for the text on the first run, and from then ignored it, and just watched the output files change.  

Now it looks for the watch text every time it gets new stdout (as this is the trigger that a build has started), and waits for the text to appear.  So if a build errors, it really times out as it doesn't show the text we are looking for.

It needs some thought as in the new world I'm not sure what the best answer is.

**Comment by cliftonc** [comment]
Ok, I have an idea.  If we timeout, we will just go back to watching stdout again as if the build succeeded, so if you fix the problem and the build starts again it should set itself right.

However we do need to show the output of the build cmd in this case so that you can see what went wrong.

**Comment by bettiolo** [comment]
Note to self, test these changes by ensuring that if webpack bombs out, the CDN will still pick up changes.

**Comment by bettiolo** [comment]
In the scenario where file monitoring is working, and the CDN build fails, on the next file system change, the build will be re-executed.
