### ISSUE TITLE
bosco cdn behaves differently than bosco s3push

### ISSUE THREAD

**Issue by bettiolo** [tes/bosco#182]
I am trying to serve font-awesome from our cdn and I am getting different behavious with `bosco cdn` and `bosco s3push`: 

config:

```
"files": {
  "font-awesome-4.5.0": {
      "basePath": "/src/client/css/compiled",
      "css": [
        "font-awesome-4.5.0/css/font-awesome.min.css"
      ],
      "fonts": [
        "font-awesome-4.5.0/fonts/FontAwesome.otf",
        "font-awesome-4.5.0/fonts/fontawesome-webfont.eot",
        "font-awesome-4.5.0/fonts/fontawesome-webfont.svg",
        "font-awesome-4.5.0/fonts/fontawesome-webfont.ttf",
        "font-awesome-4.5.0/fonts/fontawesome-webfont.woff",
        "font-awesome-4.5.0/fonts/fontawesome-webfont.woff2"
      ]
    }
}
```

`bosco cdn` doesn't bundle the css and leaves it in the expected folder:

![screen shot 2016-10-04 at 17 21 29](https://cloud.githubusercontent.com/assets/1333608/19083056/90891c4a-8a58-11e6-9809-0c7bb64fdaf5.png)

`bosco s3push` bundles the css and put's it in a different folder breaking font-awesome's relative link for fonts:

```
[04:07:49] Bosco: Pushed to S3: https://duqxiy1o2cbw6.cloudfront.net/tes/site-assets/1769/css/font-awesome-4.5.0.css
```

**Comment by cliftonc** [comment]
Change the base path so relative links work.

**Comment by cliftonc** [comment]
Also, `bosco cdn minify` duplicates the s3push process locally.

**Comment by bettiolo** [comment]
@cliftonc what do you mean by "Change the base path so relative links work"?

**Comment by cliftonc** [comment]
Remove the repeated folder name and put it in the base path, can show you tomorrow.  Bosco can't parse the CSS for relative urls, you have to be careful when creating bundles that contain CSS and relative assets.

**Comment by cliftonc** [comment]
font-awesome-4.5.0

**Comment by bettiolo** [comment]
I tried without the 'font-awesome-4.5.0' part and I had a different problem, I was loosing the versioning.

We should make the behaviour of bosco cdn the same as s3push by default, I think, otherwise the markup will be broken either locally or when deployed

**Comment by cliftonc** [comment]
If only life was that simple, let's discuss tomorrow.

**Comment by cliftonc** [comment]
I assume the immediate issue is now solved due to the library changes? If so, can we close?

**Comment by bettiolo** [comment]
Practically we are not using this anymore as we added new features to page composer that handles this better, see 'cx-library' feature there.
