### ISSUE TITLE
Bosco should tell me why it cannot start a dependency

### ISSUE THREAD

**Issue by bettiolo** [tes/bosco#189]
Bosco is telling me that it is unable to start some services, great! But why can't they be started? Probably the files are not on disk?

<img width="625" alt="screen shot 2016-10-31 at 19 35 13" src="https://cloud.githubusercontent.com/assets/1333608/19851444/3ea7dde0-9fa1-11e6-837f-00e9306073d1.png">

**Comment by geophree** [comment]
Yeah, they're non-docker remote services.  It only knows how to start remote docker services.

**Comment by cliftonc** [comment]
The message isn't good - it should be `Unable to locate and start dependencies:`

**Comment by cliftonc** [comment]
This should also now be fixed with the latest round of changes, it will actually go and start all of these for you as docker containers.
