### ISSUE TITLE
Allow globbing / stable paths for svg icons

### ISSUE THREAD

**Issue by jonnywyatt** [tes/bosco#190]
We're currently inlining our SVG icons into the main stylesheet, which is bad for performance (creates a much larger blocking CSS download, means we don't leverage caching as well as we could).

Ideally we could use the new [vendor/library mechanism](https://github.com/tes/service-site-assets/blob/master/bosco-service.json#L21-L26) to serve SVG icons on stable paths (ie not including the build number). 

A fingerprint / hash could be applied to the filename so that if the icon changes the new version will be served.

**Comment by cliftonc** [comment]
Can't you just do this in the project build step and link to in the library section?  Not sure we need to change anything to do this.

**Comment by jonnywyatt** [comment]
I started doing that yes. The key name 'libraries' could be better named though, so it implies we can use it for any asset that we want a stable path for.
