### ISSUE TITLE
Running project without a team, improve errors

### ISSUE THREAD

**Issue by bettiolo** [tes/bosco#209]
- Make a new folder
- DO NOT SETUP A TEAM
- Clone a project
- Go to the project
- npm install
- bosco run -d

You will get a lot of: "Service undefined could not be run because I was unable to find any run configuration". 

Expected:
- It should tell me that I don't have a team setup. 
- It should tell the name of the Service it cannot resolve instead of undefined

**Comment by cliftonc** [comment]
This should all be fixed and clearer in the latest round of improvements, can you retest?  It will actually just run the service and all of it's dependencies via docker.

**Comment by bettiolo** [comment]
<img width="842" alt="screen shot 2017-02-28 at 18 54 16" src="https://cloud.githubusercontent.com/assets/1333608/23457965/fa0b09a2-fe71-11e6-9095-f606bc366d52.png">

Looks ok
