### ISSUE TITLE
Bosco is caching the docker ExtraHosts config

### ISSUE THREAD

**Issue by tomruttle** [tes/bosco#218]
This is inserted into the hosts file for a container. If your host ip address changes, containers can no longer talk to the host.

Temporary work around:

```
docker exec -it page-composer /etc/hosts
```

Look for the `local.tescloud.com` entry that doesn't correspond to your current ip (there will be two `local.tescloud.com` entries if this is the case), then remove all occurrences of that ip address from your `~/.bosco/bosco.json` file.

**Comment by cliftonc** [comment]
You can also just run bosco with --nocache.  But will modify so that is always re-evaluated on run.

**Comment by cliftonc** [comment]
This should be evaluated on every run - so if you restart you should be ok?  Can you confirm?

**Comment by tomruttle** [comment]
Yep, LGTM
