### ISSUE TITLE
Bosco install not respecting nvmrc when using yarn

### ISSUE THREAD

**Issue by geophree** [tes/bosco#224]
`bosco install` doesn't respect `.nvmrc` when the project is using `yarn` to manage their `node_modules`.

We just need to pull the interpreter stuff out a level so it applies to both `npm` and `yarn`.
https://github.com/tes/bosco/blob/master/commands/install.js#L26-L90

**Comment by Jae** [comment]
bosco respects .nvmrc when npm is used.

**Comment by Jae** [comment]
done as of https://github.com/tes/bosco/pull/225
