### ISSUE TITLE
Bosco service/app/infra blacklist

### ISSUE THREAD

**Issue by geophree** [tes/bosco#228]
`app-resource` runs a bunch of things I don't care about most of the time when developing on it.  This can bring my machine to its knees, even with 16 gigs of RAM.  I'd like a way to say something like "don't run these services unless -r explicitly matches them".

**Comment by cliftonc** [comment]
So basically make the regex value of `-r` pass down and filter the dependencies?

**Comment by cliftonc** [comment]
Fixed!
