### ISSUE TITLE
split bosco

### ISSUE THREAD

**Issue by csabapalfi** [tes/bosco#37]
bosco is maybe doing a bit too much:
* dealing with multiple github repos (clone, pull, status, ...)
* running a set of microservices and docker containers
* assets/cdn

It'd be much easier to reason about what's going on if these pieces were somewhat separate. ( Some ideas: complete separation, command-groups via npm modules, ?)

What do you think?

**Comment by cliftonc** [comment]
I'm going to close this, as apart from potentially renaming a command I can't see a way we can use Bosco to do consistent static asset building on a build server and not having bosco cdn locally to replicate it for dev.

We could however break chunks of Bosco out into separate libraries and so reduce the code breadth in it, but that's a different set of tasks.

**Comment by csabapalfi** [comment]
:+1:

**Comment by gabceb** [comment]
#51 should make it easier to split Bosco when pulled
