### ISSUE TITLE
Streaming CmdHelper and Exec command

### ISSUE THREAD

**Issue by cliftonc** [tes/bosco#49]
Follow on discussion with #43

See commit: 0c7598f56f3a5a3c61799e571ff823cffe058408

Easy to test running:  

```
bosco exec -- ping www.google.com
```

**Comment by cliftonc** [comment]
Geoff - I'm OK with this - when I'm finished with all the tweaking around config and teams in https://github.com/tes/bosco/tree/0.4.0 and get that into master I'll sweep through all the commands and migrate them to use this approach.

**Comment by geophree** [comment]
Sounds good to me.

P.S.  It's Jeff.

**Comment by cliftonc** [comment]
Sorry - your github name threw me when in doubt :)

**Comment by cliftonc** [comment]
Will close this and create a new issue with separate tasks for each command now that this is in good shape.
