### ISSUE TITLE
Bosco status not showing the service/repo name which has uncommitted changes

### ISSUE THREAD

**Issue by aamirafridi** [tes/bosco#50]
Whey you try ```bosco status``` and a repo has uncommitted changes, it just shows you that repo has changes and there is no way to find which repo.

![example of bosco status issue](https://cloud.githubusercontent.com/assets/55896/5679678/afd5110a-97fa-11e4-8247-a5d6938d249f.png)

**Comment by aamirafridi** [comment]
@cliftonc hope this was the issue https://github.com/tes/bosco/commit/49dc4569877ce67df737b520b305fd61485d9990

**Comment by cliftonc** [comment]
Lgtm!
