### ISSUE TITLE
Bosco 0.4 should use appropriate directories to store data (XDG on Linux)

### ISSUE THREAD

**Issue by geophree** [tes/bosco#55]
If we're going to store data in a user's home directory, we should use XDG_* directories on Linux, and probably the platform-specific ones on Mac/Win.  We can do this with the following node package:
https://github.com/MrJohz/appdirectory
https://www.npmjs.com/package/appdirectory

At a minimum we should use that package on linux.

Background:
XDG base-dir spec:
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
How qt does it:
http://qt-project.org/doc/qt-4.8/qsettings.html#locations-where-application-settings-are-stored

**Comment by cliftonc** [comment]
Agree, I am keen to get 0.4 up to master, I held back due to resources go live but the new way of managing config and teams is much much better in this.

What are peoples thoughts on publishing as is?

**Comment by geophree** [comment]
That doesn't do what I wanted for this issue.  I'd like it to follow the XDG spec on linux for the location of config, cache, and data.  The appdirectory module will do it, but it may not do what you want on mac/windows though.  My main concern is linux, I don't want it to add another dotfile/dotdir to my home folder, and I'd like any cache to be separated out into a cache directory.

**Comment by codeaholics** [comment]
+1

**Comment by cliftonc** [comment]
No issue if you want to take it further, given you two are our most vocal Linux users you can decide between yourselves who wants to pick it up ;)

**Comment by geophree** [comment]
I have changes for this locally, I need to write some tests.
