### ISSUE TITLE
Pass double-dashes (--) to commands correctly

### ISSUE THREAD

**Issue by geophree** [tes/bosco#64]
We should only be stripping off the first -- from the command line.  It looks like commander (our option-parsing library) strips them all out.  This makes it impossible to grep and force to a file (it thinks it's ambiguously a file or revision).  It could also mess up exec.

**Comment by geophree** [comment]
We could look into https://github.com/nodeca/argparse, I quite like the python version of that library.

**Comment by Josiah** [comment]
[`minimist`](https://github.com/substack/minimist) from substack is a brilliant library for command line argument parsing

It supports double dashes and just about everything else out of the box

**Comment by geophree** [comment]
commander ostensibly supports it as well, it's just doing it incorrectly (in my opinion).  I think `minimist` might be a little too minimal for what we're trying to do.  If we're really against argparse, [`yargs`](https://github.com/bcoe/yargs) looks like it could work, assuming it treats `--` correctly.

**Comment by orangejuicecoder** [comment]
+1

**Comment by orangejuicecoder** [comment]
hype
