### ISSUE TITLE
Bosco CDN no longer generating asset html

### ISSUE THREAD

**Issue by Josiah** [tes/bosco#66]
Bosco is now generating the following instead of generating the `<script>` tags for html fragments:

```js
function (obj) {
obj || (obj = {});
var __t, __p = '';
with (obj) {
__p += '<script src="' +
((__t = ( url )) == null ? '' : __t) +
'"></script>\n';

}
return __p
}
```

**Comment by cliftonc** [comment]
This was due to the upgrade of lodash, and the change of api in lodash template.

Fixed:  https://github.com/tes/bosco/commit/bc50501faca96e71b130d9d92c9b2cc383a4795b
