### ISSUE TITLE
Breaking change in 0.4.9

### ISSUE THREAD

**Issue by tomgco** [tes/bosco#68]
In https://github.com/tes/bosco/commit/644ec3c4d2565f4936f684b8e0d1433b1ce98157 As far as I can tell the urls which are being generated by bosco cdn has now changed.

from:

```
http://local.tescloud.com:7334/registration/local/widget.js
```

to:

```
http://local.tescloud.com:7334/widget/registration/local/widget.js
```

Below is my bosco-service.json:

```json
{
  "tags": [ "registration" ],
  "build": {
    "command": "node_modules/.bin/gulp"
  },
  "assets": {
    "basePath": "/build-dev/",
    "js": {
      "widget": [
        "widget.js"
      ],
      "vendor": [
        "es5-shim.min.js",
        "jquery-1.11.1.min.js",
        "bootstrap.min.js",
        "jquery.mockjax.js",
        "validator.min.js",
        "iframeResizer.contentWindow.min.js",
        "jquery.xdomainrequest.min.js",
        "placeholders.min.js",
        "ie7.min.js"
      ],
      "src": [
        "util.js",
        "main.js"
      ]
    },
    "html": {
      "widget": [
        "index.html"
      ]
    },
    "css": {
      "vendor": [
        "bootstrap.min.css",
        "bootstrap.flatly.min.css"
      ],
      "src": [
        "style.css"
      ]
    }
  }
}

```

Do we have a way to have the old functionality, if not then should this be released as a bosco major version?

**Comment by cliftonc** [comment]
It shouldn't have changed the bundle URLs, but looks like I missed unminified local CDN usage - will take a look.

**Comment by cliftonc** [comment]
Yep @tomgco it is definitely now a different url.

Not one that I had considered at the time as Page Composer always uses the HTML fragments locally (not calling the JS directly), and as the change in path was reflected in the fragments not an issue there.

Let me have another go at the code, as I suspect I can refactor it to keep those paths the same but still allow for the bundles to share assets somehow ...

I'd prefer not to attempt to re-write history re. publishing this as a 0.5 given what work has followed.

**Comment by cliftonc** [comment]
In the interim if you use 'bosco cdn minify' it will work as before.

**Comment by cliftonc** [comment]
Note that this will be resolved without the 'hack' by https://github.com/tes/bosco/pull/72

**Comment by cliftonc** [comment]
@tomgco  - be great if you can confirm this now works as expected so we can close.

**Comment by tomgco** [comment]
@cliftonc This version works :D :dart:

**Comment by cliftonc** [comment]
Hooray!
