### ISSUE TITLE
Pull for branch rather than master

### ISSUE THREAD

**Issue by tomchambers2** [tes/bosco#73]
Any reason why https://github.com/tes/bosco/blob/e471a1e17e2d1aa8eaadbd6dc625eabf20c0a609/commands/pull.js#L100 needs to come from origin master rather than letting git find the matching branch?

**Comment by cliftonc** [comment]
No reason I can remember, feel free to change and submit a PR if it's causing you a problem.

**Comment by codeaholics** [comment]
Not that I'm aware of. And I vaguely recall it causing some problems in the past. Remember that the clones are created up by Bosco, so we need to ensure that they are set up with correct upstream tracking.
