### ISSUE TITLE
bosco cdn watch doesn't show any gulp errors

### ISSUE THREAD

**Issue by aamirafridi** [tes/bosco#84]
if you have some error in sass for example, gulp will show the error message but bosco cdn watch will remain silent. You have to run gulp separately to see any errors. It will be nice if bosco cdn watch shows you the message.

**Comment by cliftonc** [comment]
@geophree did some work on this so that errors didn't break you out of cdn mode, can you assist?

**Comment by dbellizzi** [comment]
Which repository is having issues?  It is usually the gulp file that needs changing

**Comment by geophree** [comment]
There are a few problems:
- watch dies on errors
- build doesn't fail on errors
- cdn doesn't show errors

The solutions to these are often intertwined.  When you fix the first one, the second becomes an issue.  The solution to the third is to make sure we always output errors to stderr.

I pushed a commit for service-site-assets that converts it to a better way, we may be able to pull it out into a module or something to make it even easier.  See https://github.com/tes/service-site-assets/commit/1da5e8879c821e4b0a7036beaabf85ca40e13494

**Comment by geophree** [comment]
For those reading without access to tes, using gulp plumber and an error logging function that we switch out when doing a watch:
```js
var HandleErrors = (function() {
    function HandleErrors() {
        return GulpPlumber(plumberOptions);
    }

    function printError(err) {
        var msg = 'Error';
        if (err.fileName) {
            msg += ' in "' + err.fileName + '"';
        }
        if (err.lineNumber) {
            msg += ' on line ' + err.lineNumber;
        }
        // output to stderr, that's where errors belong
        console.error(msg + ':', err.message);
    }

    var plumberOptions = {
        errorHandler: function(err) {
            printError(err);
            // throw the error to end the build with non-0 exit code
            throw err;
        }
    };

    HandleErrors.setupWatch = function() {
        plumberOptions.errorHandler = function(err) {
            printError(err);
            // stop the error propagation so our watch doesn't die
            this.emit('end');
        };
    };
    return HandleErrors;
})();
// then later:
Gulp.task('build:sass',  function () {
    return Gulp.src(paths.sass)
      .pipe(HandleErrors())
      .pipe(Sass())
      //...

//and
Gulp.task('watch:sass', function () {
    HandleErrors.setupWatch();
    Gulp.watch(paths.sass, ['build:sass']);
});
```
