### ISSUE TITLE
0.4.30 breaks bosco start

### ISSUE THREAD

**Issue by tomgco** [tes/bosco#87]
```
Starting app-resource via /Users/tomgco ...
```

Docker containers seem to start, however applications do not.

Running `0.10.38` using `nave`.

**Comment by tomgco** [comment]
I assume this is because bosco now has a hard dependancy on `nvm`

**Comment by cliftonc** [comment]
Let me check, if you specify an engine it will look for the node version in the nvm path, but if you don't it should just start it.

**Comment by cliftonc** [comment]
Sorry - see the issue, will fix.

**Comment by cliftonc** [comment]
Fixed with Bosco published to 0.4.31.
