### ISSUE TITLE
A failed app build should fail the jenkins build

### ISSUE THREAD

**Issue by jonnywyatt** [tes/bosco#98]
eg. if the bosco build maps to a gulp build which fails, the whole jenkins build should fail

**Comment by geophree** [comment]
Example?

**Comment by jonnywyatt** [comment]
http://jenkins.tescloud.com/job/service-site-assets/555/consoleFull

'gulp build' for service-site-assets - if it fails, the stylesheet isn't uploaded to the CDN so the page loses all styling

**Comment by cliftonc** [comment]
I think we ignore errors in the build:  

https://github.com/tes/bosco/blob/master/src/ExternalBuild.js#L26

When in s3push mode we should probably send the error up the stack and ensure we exit in a way that breaks the build.

**Comment by cliftonc** [comment]
@geophree you did work around here to make sure CDN kept running even if builds failed (so they would recover) - do you think just adding a switch to the build process will do it: onFailedBuild = ignore || fail - so when doing the s3push we can have the build fail and exit with error?

**Comment by geophree** [comment]
I think this commit will solve our problems: https://github.com/tes/bosco/commit/ca981fd59047881839dd30e34d442121fa4d4830
but I haven't fully tested it yet.  Also, adding my s3push test caused the tests to fail because it reduced the percentage coverage.  I'll do more testing in 10 hours or so.
